/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herramienta.liquidacion.interfaz;

import javax.swing.JOptionPane;

import herramienta.liquidacion.mundo.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author CRUEDA
 */
public class InterfazHerramientaLiquidacion extends javax.swing.JFrame {

    private Persona persona;
    private final long MILLSECS_PER_DAY = 24 * 60 * 60 * 1000;
    private final int AUXTXLEGAL = 83140;
    private final int SALMINLEGAL = 737717;

    private InterfazComprobantePagoSalarioMensual jfrmComPagSalMen;
    private InterfazComprobantePagoLiquidacion jfrmComPagLiquidacion;
    private InterfazComprobantePagoIndemnizacion jfrmComPagIndemnizacion;

    /**
     * Creates new form InterfazHerramientaLiquidacion
     */
    public InterfazHerramientaLiquidacion() {
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.LIGHT_GRAY);

        //Se agregan los botones de C.C. y C.E. al botongroup
        btngrpTipoDocumento.add(jrbtnCC);
        btngrpTipoDocumento.add(jrbtnCE);

        //Se agregan los botones de Salario, liquidación e Indenmización 
        //al botongroup
        btngrpTipoCalculo.add(jrbtnSalario);
        btngrpTipoCalculo.add(jrbtnLiquidacion);
        btngrpTipoCalculo.add(jrbtnIndenmizacion);

        persona = new Persona();
        limpiarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpTipoDocumento = new javax.swing.ButtonGroup();
        btngrpTipoCalculo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jrbtnCC = new javax.swing.JRadioButton();
        jrbtnCE = new javax.swing.JRadioButton();
        jtxtNumDoc = new javax.swing.JTextField();
        jtxtPrimerNom = new javax.swing.JTextField();
        jtxtSegNombre = new javax.swing.JTextField();
        jtxtPrimerApel = new javax.swing.JTextField();
        jtxtSegApel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jfmtxtInicio = new javax.swing.JFormattedTextField();
        jfmtxtFin = new javax.swing.JFormattedTextField();
        jrbtnSalario = new javax.swing.JRadioButton();
        jrbtnLiquidacion = new javax.swing.JRadioButton();
        jrbtnIndenmizacion = new javax.swing.JRadioButton();
        jbtnCalcular = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jftxtSalBas = new javax.swing.JFormattedTextField();
        jftxtAuxTx = new javax.swing.JFormattedTextField();
        jftxtDiasLab = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Herramienta de liquidación");
        setBackground(java.awt.Color.lightGray);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Herramienta de Liquidación");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tipo de documento");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de cálculo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Primer nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Segundo nombre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fin");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Auxilio de transporte");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Primer apellido");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Segundo apellido");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Dias laborados");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Número de documento");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Inicio");

        jrbtnCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnCC.setText("C.C.");

        jrbtnCE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnCE.setText("C.E");

        jtxtNumDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtNumDoc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtNumDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jtxtPrimerNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtPrimerNom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtPrimerNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jtxtSegNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtSegNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtSegNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jtxtPrimerApel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtPrimerApel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtPrimerApel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jtxtSegApel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtSegApel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtSegApel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Salario básico");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Periodo liquidado");

        jfmtxtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MMM-yyyy"))));
        jfmtxtInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmtxtInicio.setToolTipText("dd-mes-yyyy (i.e.: 12-may-2017)");
        jfmtxtInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jfmtxtInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jfmtxtFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MMM-yyyy"))));
        jfmtxtFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmtxtFin.setToolTipText("dd-mes-yyyy (i.e.: 12-may-2017)");
        jfmtxtFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jfmtxtFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jrbtnSalario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnSalario.setText("Salario");

        jrbtnLiquidacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnLiquidacion.setText("Liquidación");

        jrbtnIndenmizacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnIndenmizacion.setText("Indemnización");

        jbtnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnCalcular.setMnemonic('C');
        jbtnCalcular.setText("Calcular");
        jbtnCalcular.setToolTipText("Calcula el salario");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jbtnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLimpiar.setMnemonic('l');
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.setToolTipText("Limpia el formulario");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnSalir.setMnemonic('s');
        jbtnSalir.setText("Salir");
        jbtnSalir.setToolTipText("Sale de la aplicación");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jftxtSalBas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        jftxtSalBas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftxtSalBas.setToolTipText("i.e.: $747000");
        jftxtSalBas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jftxtSalBas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        jftxtAuxTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        jftxtAuxTx.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftxtAuxTx.setToolTipText("i.e.: $54000");
        jftxtAuxTx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jftxtAuxTx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });
        jftxtAuxTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtAuxTxActionPerformed(evt);
            }
        });

        jftxtDiasLab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        jftxtDiasLab.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftxtDiasLab.setToolTipText("i.e.: 15");
        jftxtDiasLab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jftxtDiasLab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPrimerNom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPrimerApel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSegApel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jfmtxtFin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfmtxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jtxtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbtnIndenmizacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jrbtnSalario)
                                        .addGap(61, 61, 61)
                                        .addComponent(jrbtnLiquidacion)
                                        .addGap(159, 159, 159))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jftxtDiasLab, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftxtSalBas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftxtAuxTx, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jrbtnCC)
                        .addGap(18, 18, 18)
                        .addComponent(jrbtnCE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jrbtnCC)
                    .addComponent(jrbtnCE)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtxtPrimerNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jtxtSegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jtxtPrimerApel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jfmtxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(jtxtSegApel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jfmtxtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18)
                    .addComponent(jLabel9)
                    .addComponent(jftxtSalBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtAuxTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtDiasLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrbtnSalario)
                    .addComponent(jrbtnLiquidacion)
                    .addComponent(jrbtnIndenmizacion))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnCalcular)
                    .addComponent(jbtnLimpiar)
                    .addComponent(jbtnSalir))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        //Asignar el tipo de documento a la persona
        if (jrbtnCC.isSelected()) {
            persona.setTipodoc(TipoDocumento.CC);
        } else {
            persona.setTipodoc(TipoDocumento.CE);
        }

        //Validar el primer nombre
        String strnombre = jtxtPrimerNom.getText();
        strnombre = strnombre.trim();
        if (strnombre.isEmpty()) {
            jtxtPrimerNom.requestFocus();
            JOptionPane.showMessageDialog(null, "Nombre invalido",
                "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        persona.setPrimNombre(strnombre);

        //Validar el segundo nombre. Si es vacio no importa
        String strsegnombre = jtxtSegNombre.getText();
        strsegnombre = strsegnombre.trim();
        persona.setSegNombre(strsegnombre);

        //Validar el primer apellido
        String strapel = jtxtPrimerApel.getText();
        strapel = strapel.trim();
        if (strnombre.isEmpty()) {
            jtxtPrimerApel.requestFocus();
            JOptionPane.showMessageDialog(null, "Primer Apellido invalido",
                "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        persona.setPrimApel(strapel);

        //Validar el segundo Apellido. Si es vacio no importa
        String strsegapel = jtxtSegApel.getText();
        strsegapel = strsegapel.trim();
        persona.setSegApel(strsegapel);

        //Validar el numero de documento
        String strnumdoc = jtxtNumDoc.getText();
        strnumdoc = strnumdoc.trim();
        if (strnumdoc.isEmpty()) {
            jtxtNumDoc.requestFocus();
            JOptionPane.showMessageDialog(null, "Número de documento inválido",
                "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        persona.setNumdoc(strnumdoc);

        //validar dias laborados
        long diaslab = 0;
        try {
            diaslab = (long) jftxtDiasLab.getValue();
        } catch (NumberFormatException ex) {
            jftxtDiasLab.requestFocus();
            JOptionPane.showMessageDialog(null, "Días laborados inválido. \n"
                + ex.getMessage(), "Herramienta de liquidación",
                JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception ex) {
            jftxtDiasLab.requestFocus();
            JOptionPane.showMessageDialog(null, "Error. Días laborados inválido. \n"
                + ex.getMessage(), "Herramienta de liquidación",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jrbtnSalario.isSelected() && ((diaslab <= 0) || (diaslab > 30))) {
            //Si es calculo de salario y los dias son mayores a 30
            jftxtDiasLab.requestFocus();
            JOptionPane.showMessageDialog(null, "Días laborados inválidos",
                "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        persona.setDiastrab((int) diaslab);

        //validar salario basico
        long salbas = 0;
        try {
            salbas = (long) jftxtSalBas.getValue();
        } catch (NumberFormatException ex) {
            jftxtSalBas.requestFocus();
            JOptionPane.showMessageDialog(null, "Salario básico inválido. \n"
                + ex.getMessage(), "Herramienta de liquidación",
                JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception ex) {
            jftxtSalBas.requestFocus();
            JOptionPane.showMessageDialog(null, "Error. Salario básico inválido. \n"
                + ex.getMessage(), "Herramienta de liquidación",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (salbas <= 0) {
            //Si es negativo
            jftxtSalBas.requestFocus();
            JOptionPane.showMessageDialog(null, "Salario básico inválido",
                "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        persona.setSalbas((int) salbas);

        //validar auxilio de transporte
        long auxtx = 0;
        try {
            auxtx = (long) jftxtAuxTx.getValue();
        } catch (NumberFormatException ex) {
            jftxtAuxTx.requestFocus();
            JOptionPane.showMessageDialog(null, "Auxilio de transporte inválido. \n"
                + ex.getMessage(), "Herramienta de liquidación",
                JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception ex) {
            jftxtAuxTx.requestFocus();
            JOptionPane.showMessageDialog(null, "Error. Auxilio de transporte inválido. \n"
                + ex.getMessage(), "Herramienta de liquidación",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (auxtx <= 0) {
            //Si es negativo
            jftxtAuxTx.requestFocus();
            JOptionPane.showMessageDialog(null, "Salario básico inválido",
                "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        persona.setAuxtrans((int) auxtx);
        System.out.println("Auxilio de tx: " + persona.getAuxtrans());

        if (jrbtnLiquidacion.isSelected()) {
            //Validar Periodo Inicio
            String strperini = jfmtxtInicio.getText();
            strperini = strperini.trim();
            if (strperini.isEmpty() || strperini == null) {
                //Si es vacio
                jfmtxtInicio.requestFocus();
                JOptionPane.showMessageDialog(null, "Fecha de periodo de inicio inválido",
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat formatdate = new SimpleDateFormat("dd-MMM-yyyy");
            Date dateini;
            try {
                dateini = formatdate.parse(strperini);
            } catch (ParseException ex) {
                jfmtxtFin.requestFocus();
                JOptionPane.showMessageDialog(null,
                    "Fecha de periodo de inicio inválido\n" + ex.getMessage(),
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            } catch (Exception ex) {
                jfmtxtFin.requestFocus();
                JOptionPane.showMessageDialog(null,
                    "Fecha de periodo de inicio inválido\n" + ex.getMessage(),
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //Validar Periodo Fin
            String strperfin = jfmtxtFin.getText();
            strperfin = strperfin.trim();
            if (strperfin.isEmpty() || strperfin == null) {
                //Si es vacio
                jfmtxtFin.requestFocus();
                JOptionPane.showMessageDialog(null, "Fecha de periodo de inicio inválido",
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Date datefin;
            try {
                datefin = formatdate.parse(strperfin);
            } catch (ParseException ex) {
                jfmtxtFin.requestFocus();
                JOptionPane.showMessageDialog(null,
                    "Fecha de periodo de inicio inválido\n" + ex.getMessage(),
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            } catch (Exception ex) {
                jfmtxtFin.requestFocus();
                JOptionPane.showMessageDialog(null,
                    "Fecha de periodo de inicio inválido\n" + ex.getMessage(),
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //Validar Period Fin > Inicio
            if (datefin.before(dateini)) {
                //Fecha de fin menor a fecha ini
                jfmtxtFin.requestFocus();
                JOptionPane.showMessageDialog(null,
                    "Fecha de fin de periodo debe ser mayor o igual a la fecha de inicio de periodo",
                    "Herramienta de liquidación", JOptionPane.ERROR_MESSAGE);
                return;
            }
            persona.setPerinicio(dateini);
            persona.setPerfin(datefin);

            //Asignar Periodo Incio y Fin
            long diasperiodo = (datefin.getTime() - dateini.getTime()) / MILLSECS_PER_DAY;
            persona.setDiasperiodo(diasperiodo);
        } else {
            persona.setPerinicio(null);
            persona.setPerfin(null);
            persona.setDiasperiodo(0);
        }

        if (jrbtnSalario.isSelected()) {
            //Si se seleccionó el tipo de calculo: Salario
            //Calcular salario devengado
            calcularSalDevengado();

            //Muestra el formulario
            if (jfrmComPagSalMen == null) {
                jfrmComPagSalMen = new InterfazComprobantePagoSalarioMensual(persona);
            } else {
                jfrmComPagSalMen.setPersona(persona);
                jfrmComPagSalMen.cargarFormulario();
            }
            jfrmComPagSalMen.setAlwaysOnTop(true);
            jfrmComPagSalMen.setVisible(true);
        } else if (jrbtnLiquidacion.isSelected()) {
            //Si se seleccionó el tipo de calculo: Liquidacion
            //Calcular de la liquidación
            persona.setDiastrab((int) persona.getDiasperiodo());
            jftxtDiasLab.setValue((long) persona.getDiastrab());
            calcularLiquidacion();

            //Muestra el formulario
            if (jfrmComPagLiquidacion == null) {
                jfrmComPagLiquidacion = new InterfazComprobantePagoLiquidacion(persona);
            } else {
                jfrmComPagLiquidacion.setPersona(persona);
                jfrmComPagLiquidacion.cargarFormulario();
            }
            jfrmComPagLiquidacion.setAlwaysOnTop(true);
            jfrmComPagLiquidacion.setVisible(true);
        } else if (jrbtnIndenmizacion.isSelected()) {
            //Si se seleccionó el tipo de calculo: Indemnizacion
            //Calcular de la Indemnizacion
            persona.setDiastrab((int) persona.getDiasperiodo());
            jftxtDiasLab.setValue((long) persona.getDiastrab());
            //calcularIndemnizacion();

            //Muestra el formulario
            if (jfrmComPagIndemnizacion == null) {
                jfrmComPagIndemnizacion = new InterfazComprobantePagoIndemnizacion(persona);
            } else {
                jfrmComPagIndemnizacion.setPersona(persona);
                jfrmComPagIndemnizacion.cargarFormulario();
            }
            jfrmComPagIndemnizacion.setAlwaysOnTop(true);
            jfrmComPagIndemnizacion.setVisible(true);
        }

    }//GEN-LAST:event_jbtnCalcularActionPerformed

    private void jtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtFocusGained
        ((javax.swing.JTextField) evt.getComponent()).setBackground(java.awt.Color.YELLOW);
    }//GEN-LAST:event_jtxtFocusGained

    private void jtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtFocusLost
        ((javax.swing.JTextField) evt.getComponent()).setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_jtxtFocusLost

    private void jftxtAuxTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtAuxTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtAuxTxActionPerformed

    //*************** MIS METODOS **************
    private void calcularLiquidacion() {
        int diasperiodo = (int) persona.getDiasperiodo();
        int salbas = persona.getSalbas();
        int bonoAuxTx = persona.getAuxtrans();
        int saldev = 0;
        int prima = 0;
        int cesantias = 0;
        int vacaciones = 0;
        int intcesantias = 0;
        int nummeslab = 0;
        int totLiquidacion = 0;

        if (saldev > SALMINLEGAL * 2) {
            bonoAuxTx = 0;
        }
        saldev = salbas + bonoAuxTx;

        prima = Math.round(saldev / 360.0f * diasperiodo);
        persona.setPrima(prima);

        cesantias = Math.round(saldev / 360.0f * diasperiodo);
        persona.setCesantias(cesantias);

        vacaciones = Math.round(salbas / 720.0f * diasperiodo);
        persona.setVacaciones(vacaciones);

        nummeslab = Math.round(diasperiodo / 30.0f);
        intcesantias = Math.round(cesantias * (0.01f * nummeslab));
        persona.setIntcesantias(intcesantias);

        totLiquidacion = prima + cesantias + vacaciones + intcesantias;
        persona.setLiquidacion(totLiquidacion);
    }

    private void calcularSalDevengado() {
        //Calcula el salario devengado
        int salbas = persona.getSalbas();
        int saldev = 0;
        int bonoAuxTx = persona.getAuxtrans();
        int desEps = 0;
        int desPen = 0;
        int salNeto = 0;
        int diasTrab = persona.getDiastrab();

        if (diasTrab < 30) {
            saldev = salbas / 30 * diasTrab;
            if (saldev <= SALMINLEGAL * 2) {
                bonoAuxTx = bonoAuxTx / 30 * diasTrab;
            }
        } else {
            saldev = salbas;
            if (saldev > SALMINLEGAL * 2) {
                bonoAuxTx = 0;
            }
        }
        desEps = Math.round(saldev * 0.04f);
        desPen = Math.round(saldev * 0.04f);

        salNeto = saldev - desEps - desPen + bonoAuxTx;

        persona.setSaldevengado(saldev);
        persona.setBonoAuxTx(bonoAuxTx);
        persona.setDesEps(desEps);
        persona.setDesPension(desPen);
        persona.setSalneto(salNeto);
    }

    public boolean isNumeric(String cadena) {

        boolean resultado;

        try {

            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    private void limpiarFormulario() {
        jrbtnCC.setSelected(true);
        jrbtnSalario.setSelected(true);
        jtxtPrimerNom.setText("");
        jtxtSegNombre.setText("");
        jtxtPrimerApel.setText("");
        jtxtSegApel.setText("");
        jftxtDiasLab.setValue((long) 0);
        jftxtSalBas.setValue((long) 0);
        jftxtAuxTx.setValue((long) 0);
        //jftxtSalBas.setText("$0");
        ///jftxtAuxTx.setText("$0");
        jtxtNumDoc.setText("");
        jfmtxtInicio.setText("");
        jfmtxtFin.setText("");
    }

    /**
     * * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHerramientaLiquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHerramientaLiquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHerramientaLiquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHerramientaLiquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazHerramientaLiquidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpTipoCalculo;
    private javax.swing.ButtonGroup btngrpTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JFormattedTextField jfmtxtFin;
    private javax.swing.JFormattedTextField jfmtxtInicio;
    private javax.swing.JFormattedTextField jftxtAuxTx;
    private javax.swing.JFormattedTextField jftxtDiasLab;
    private javax.swing.JFormattedTextField jftxtSalBas;
    private javax.swing.JRadioButton jrbtnCC;
    private javax.swing.JRadioButton jrbtnCE;
    private javax.swing.JRadioButton jrbtnIndenmizacion;
    private javax.swing.JRadioButton jrbtnLiquidacion;
    private javax.swing.JRadioButton jrbtnSalario;
    private javax.swing.JTextField jtxtNumDoc;
    private javax.swing.JTextField jtxtPrimerApel;
    private javax.swing.JTextField jtxtPrimerNom;
    private javax.swing.JTextField jtxtSegApel;
    private javax.swing.JTextField jtxtSegNombre;
    // End of variables declaration//GEN-END:variables
}
